#!/bin/sh
set -o pipefail
. "$(dirname "$0")/_/husky.sh"

# これからコミットするファイルにpackage-lock.jsonが含まれていればツールを動かす
git diff --cached --name-only | grep "package-lock.json" > /dev/null || SKIP=true
if [ $SKIP ];then exit 0;fi;

FILENAME="src/constants/licenses.json"
# ツール側で余分なログを出力するところはsedでtrimする
npx license-checker --customPath .husky/customFormat.json --json --direct --unknown \
 | sed -r "s/(\"dependencyPath\": \").*(\".*)$/\1\2/" \
 | sed -r "s/(\"licenseFile\": \").*(\".*)$/\1\2/" \
 | sed -r "s/(\"path\": \").*(\".*)$/\1\2/" \
 | sed -r "s/(\"licenseText\": \").*(\".*)$/\1\2/" \
 | sed -r "s/(\"noticeFile\": \").*(\".*)$/\1\2/" \
 > $FILENAME
git add $FILENAME
